### ISSUE TITLE
Android phone Topbar not visible

### ISSUE THREAD

**Issue by djtjp** [MartinVerhey/keepscore#4]
The topbar of  android is not visible. So no time, cellular reception etcetera is not visible. Only a small black bar is visible.

**Comment by martinverhey** [comment]
Hi there. Thanks for the notice. I was able to reproduce this issue on multiple android devices and will look into it before the next release.

**Comment by martinverhey** [comment]
Thanks again @djtjp for letting me know this issue exists. It has been fixed and the new update is now live ;) Enjoy!
